/**
 * Catálogo curado de suplementos (espelha o seed de montinho.supplements).
 *
 * Dados descritivos apenas — a regra de indicação vive no motor (Documento 11).
 * Cada suplemento carrega o problema que resolve e a alternativa alimentar
 * (Documento 00 — nunca protagonista).
 */

import type { Supplement } from "@/modules/supplements/types";

export const SUPPLEMENT_CATALOG: Supplement[] = [
  {
    id: "creatine",
    name: "Creatina monohidratada",
    objective: "Força, potência e ganho de massa magra.",
    problemSolved: "Desempenho e recuperação no treino de força.",
    mechanism: "Recompõe fosfocreatina, melhorando a produção rápida de energia (ATP).",
    usualDose: "3–5 g por dia, todos os dias.",
    timing: "Qualquer horário; constância importa mais que o momento.",
    foodAlternatives: "Carne vermelha e peixe — mas seria preciso muita quantidade para a mesma dose.",
    expectedImpact: "Um dos suplementos com melhor evidência e custo-benefício.",
    evidence: "strong",
    costBenefit: "high",
    priority: 10,
  },
  {
    id: "whey",
    name: "Whey protein",
    objective: "Facilitar o fechamento da meta de proteína.",
    problemSolved: "Dificuldade de atingir a proteína diária pela comida.",
    mechanism: "Proteína de alta qualidade, prática e de rápida absorção.",
    usualDose: "1 dose (20–30 g de proteína) quando a comida não fechar.",
    timing: "No lanche ou pós-treino, conforme a rotina.",
    foodAlternatives: "Ovos, iogurte, atum, frango desfiado, queijo cottage — sempre a primeira escolha.",
    expectedImpact: "Conveniência para bater a proteína; não é obrigatório se a comida der conta.",
    evidence: "strong",
    costBenefit: "medium",
    priority: 20,
  },
  {
    id: "b12",
    name: "Vitamina B12",
    objective: "Prevenir deficiência em dietas sem carne.",
    problemSolved: "Ausência de fontes confiáveis de B12 na dieta vegana/vegetariana.",
    mechanism: "Repõe a B12, essencial ao sistema nervoso e à formação de sangue.",
    usualDose: "Conforme orientação (ex.: dose semanal), para dietas sem produtos animais.",
    timing: "Conforme o protocolo escolhido.",
    foodAlternatives: "Sem alternativa vegetal confiável — nesse caso, suplementar é o caminho seguro.",
    expectedImpact: "Prevenção de deficiência — questão de saúde, não de desempenho.",
    evidence: "strong",
    costBenefit: "high",
    priority: 15,
  },
  {
    id: "fiber",
    name: "Fibra (psyllium)",
    objective: "Saciedade e regularidade intestinal.",
    problemSolved: "Fome mal controlada e baixo volume alimentar.",
    mechanism: "Fibra solúvel que forma gel, aumenta a saciedade e regula o intestino.",
    usualDose: "5–10 g com bastante água.",
    timing: "Antes das refeições em que a fome é maior.",
    foodAlternatives: "Vegetais, aveia, leguminosas e frutas com casca — primeiro a comida.",
    expectedImpact: "Ajuda na saciedade quando a dieta ainda é pobre em fibras.",
    evidence: "moderate",
    costBenefit: "medium",
    priority: 40,
  },
  {
    id: "omega3",
    name: "Ômega-3 (EPA/DHA)",
    objective: "Suporte anti-inflamatório e cardiovascular.",
    problemSolved: "Baixo consumo de peixes gordos na rotina.",
    mechanism: "Ácidos graxos essenciais com papel anti-inflamatório e cardiovascular.",
    usualDose: "1–2 g de EPA+DHA por dia.",
    timing: "Junto a uma refeição com gordura.",
    foodAlternatives: "Sardinha, salmão e outros peixes gordos 2–3x por semana — a primeira opção.",
    expectedImpact: "Benefício de saúde quando o consumo de peixe é baixo.",
    evidence: "moderate",
    costBenefit: "medium",
    priority: 50,
  },
  {
    id: "caffeine",
    name: "Cafeína / pré-treino",
    objective: "Energia e desempenho no treino.",
    problemSolved: "Falta de disposição para treinar com qualidade.",
    mechanism: "Estimulante que reduz a percepção de esforço e melhora o foco.",
    usualDose: "3–6 mg/kg cerca de 30–45 min antes do treino.",
    timing: "Antes do treino; evitar perto do horário de dormir.",
    foodAlternatives: "Café puro antes do treino resolve na maioria dos casos.",
    expectedImpact: "Ganho agudo de desempenho; usar com moderação.",
    evidence: "strong",
    costBenefit: "high",
    priority: 45,
  },
  {
    id: "magnesium",
    name: "Magnésio",
    objective: "Apoio à qualidade do sono e relaxamento.",
    problemSolved: "Sono curto ou de baixa qualidade.",
    mechanism: "Cofator de centenas de reações; participa do relaxamento muscular e nervoso.",
    usualDose: "200–400 mg à noite.",
    timing: "À noite, antes de dormir.",
    foodAlternatives: "Folhas verdes, oleaginosas e leguminosas; além de higiene do sono.",
    expectedImpact: "Pode ajudar o sono; evidência mais modesta.",
    evidence: "limited",
    costBenefit: "medium",
    priority: 60,
  },
];
